### ISSUE TITLE
[webpack-dev-middleware] HookWebpackError: self is not defined

### ISSUE THREAD

**Issue by kumardeepakxyz** [webdiscus/pug-plugin#1]
Hi, very excited about this plugin. Really want this to work 😃 

However, I am getting the below error when trying to use it in my project (IN DEV MODE i.e webpack serve)::

`[webpack-dev-middleware] HookWebpackError: self is not defined
-- inner error --
ReferenceError: self is not defined`
![Screenshot 2021-12-24 at 1 56 12 AM](https://user-images.githubusercontent.com/36254505/147288806-0aeadae8-a8a9-4a99-b937-75d137dc22a2.png)

My Config is as follow::
`(Bare minimum for testing)`
![Screenshot 2021-12-24 at 1 59 11 AM](https://user-images.githubusercontent.com/36254505/147289017-b64c0164-4223-498d-8542-c7e2f1863898.png)

I hope you can resolve this ASAP. Let me know if I am missing something.

Thank you!

**Comment by webdiscus** [comment]
Hello @kumardeepakxyz,

thank you for usage.
Yes, I know about this limitation.
The `webpack serve`  is currently  not supported yet.
But I work to add this feature. 
The support  `webpack serve` will be added in next version of the plugin.

Currently works following modes:

`webpack --mode=production`
`webpack --mode=development`
`webpack --watch`

**Comment by kumardeepakxyz** [comment]
Okay, when is the launch of next version?

Also, how can we dynamically inject JS and CSS (from SCSS) into the templates?

**Comment by webdiscus** [comment]
> Okay, when is the launch of next version?

In lunary 2022. Now we have Christmas and Sylvester :-)

> Also, how can we dynamically inject JS and CSS (from SCSS) into the templates?

## Add JavaScript source in template

```pug
script
  include ./script.js
```

## Add JavaScript in template

I'm not sure whether following works:
```pug
head
  link(rel='stylesheet' href=require('./path/to/src/main.scss'))
  script(src='./path/to/src/main.js')
```
> to replace original asset names with hached names like `main-fjg234g52j4.js` or `styles-fdwdf6w876w.css` can be used an asstes manifest plugin to replace names.

I compile the JS, SCSS via Webpack and add compiled names of assets in template:
```pug
head
  link(rel='stylesheet' href='assets/css/styles.css')
  script(src='assets/js/main.js')
```

## Usage  JavaScript  Library in template

`say-hello.js`
   ```js
   module.exports = function (name) {
     return `Hello ${name}!`;
   }
   ```
   `pug template`
   ```pug
   - var sayHello = require('./say-hello.js')
   h1 #{ sayHello('pug') }
```

## Usage  JSON data in template

`data.json`
   ```json
   [
     { "id": 1, "name": "abc" },
     { "id": 2, "name": "xyz" }
   ]
   ```
`pug template`
   ```pug
   - var myData = require('./data.json')
   each item in myData
     div #{item.id} #{item.name}
   ```

P.S. more information and examples see by [pug-loader](https://github.com/webdiscus/pug-loader)

**Comment by kumardeepakxyz** [comment]
I will keep watch for the new version with fixed WEBPACK SERVE config as it number 1 requirement for me. Till time I will continue with html-webpack-plugin.

Enjoy your holidays 🎉

Wish you Merry Christmas & Happy New Year 🥳

**Comment by webdiscus** [comment]
@kumardeepakxyz Happy New Year!

Can you please try the version `1.2.0-alpha3`, update your `package.json`.
Now should work the `webpack serve`.

Your can try run the worked example:
```
clone https://github.com/webdiscus/pug-plugin.git
cd ./examples
npm i
npm run start
```

NEW: now supports require of styles directly in pug template without define the scss in webpack entry.
add to pug:
```pug
link(href=require('~Styles/styles.scss'))
```
add to webpack.config.js:
```js
const isProduction = process.env.NODE_ENV === 'production';
...
plugins: [
    new PugPlugin({
      modules: [
        PugPlugin.extractCss(), // add the module to extract CSS
      ],
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(css|sass|scss)$/,
        type: 'asset/resource', // add this for usage in pug, like `link(href=require('~Styles/my-styles.scss'))`,
        generator: {
          filename: 'assets/css/[name].[hash].css[query]', // save extracted style in public path
        },
        use: [ 'css-loader', 'sass-loader' ],
      },
    ],
  },
...
```

**Comment by webdiscus** [comment]
Hello @kumardeepakxyz,

new version 1.2.0 is released.

**Comment by webdiscus** [comment]
> Also, how can we dynamically inject JS and CSS (from SCSS) into the templates?

Hello @kumardeepakxyz,

I have new release `2.1.0` with dynamically injection of JS and SCSS.
Now is possible to use the source files of styles and scripts directly in pug.
```pug
link(href=require('./styles.scss') rel='stylesheet')
script(src=require('./main.js'))
```
The generated HTML contains hashed CSS and JS output filenames.
```html
<link rel="stylesheet" href="/assets/css/styles.05e4dd86.css">
<script src="/assets/js/main.f4b855d8.js"></script>
```

The required styles and scripts in pug do not need to define in the webpack entry. All required resources will be automatically handled by webpack.

The example of webpack.config.js:
```js
const PugPlugin = require('pug-plugin');
module.exports = {
  entry: {
    index: './src/index.pug' // extract html, css and js from pug
  },

  output: {
    path: path.join(__dirname, 'dist/'),
    publicPath: '/',
    // output filename for JS files
    filename: 'assets/js/[name].[contenthash:8].js'
  },

  plugins: [
    new PugPlugin({
      modules: [
        PugPlugin.extractCss({
          // output filename for CSS files
          filename: 'assets/css/[name].[contenthash:8].css'
        })
      ]
    })
  ],

  module: {
    rules: [
      {
        test: /\.pug$/,
        loader: PugPlugin.loader,
        options: {
          method: 'render', // for fastest compilation
        }
      },
      {
        test: /\.(css|sass|scss)$/,
        use: ['css-loader', 'sass-loader']
      }
    ],
  },
  // ...
};
```
