### ISSUE TITLE
Very long project rebuild

### ISSUE THREAD

**Issue by exocornet** [webdiscus/pug-plugin#100]
> @exocornet
> 
> The new pug plugin `v5.0.0` is released and based on the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin).
> 
> Try to upgrade your project to `v5`. See please the [BREAKING CHANGES](https://github.com/webdiscus/pug-plugin/blob/master/CHANGELOG.md#breaking-changes).
> 
> If the issue is still yet actual, feel free to reopen this issue.

Hello. I tried the new version of the plugin v5. Nothing changed. It still takes a long time to reassemble everything. :'((

_Originally posted by @exocornet in https://github.com/webdiscus/pug-plugin/issues/66#issuecomment-1986838585_

**Comment by webdiscus** [comment]
I have reopened the original issue #66.
