### ISSUE TITLE
Error RSPack with pug-plugin

### ISSUE THREAD

**Issue by exocornet** [webdiscus/pug-plugin#101]
I’m also trying to switch to RSPack and it shows an error adding a plugin as in this answer https://github.com/webdiscus/html-bundler-webpack-plugin/issues/55#issuecomment-1852446387 .

I would be grateful if we can fix this too. I wouldn’t want to switch to old solutions and plugins since your plugin is good and I really like it. Thank you for its development and timely support.

_Originally posted by @exocornet in https://github.com/webdiscus/pug-plugin/issues/66#issuecomment-1986839750_

**Comment by webdiscus** [comment]
This is double issue, see the #55
