### ISSUE TITLE
i18next doesn't work after pug-plugin update to 5.0.0 (windows only)

### ISSUE THREAD

**Issue by legeidaa** [webdiscus/pug-plugin#104]
I used your example from `examples/multi-language-i18next` in my project before update to 5.0.0 and it worked great.
After update, when i start dev-server, i recieve an error for each language
![image](https://github.com/webdiscus/pug-plugin/assets/58789232/8ff3ee51-7b03-4439-afae-91fa7c858347)

Then i downloaded example from github, didn’t change anything and ran project as is, and error is still the same

**Comment by webdiscus** [comment]
Hello @legeidaa,

thank you for issue report.
I will fix it!

I have tested on macOS, it works fine.

What is your OS? Windows 10, 11?
What is Node.js version? 16, 18, 20?

Thanks!

**Comment by legeidaa** [comment]
System is Windows 10 Corporate 21H2, build 19044.1526
Node version - 18.16.1

**Comment by webdiscus** [comment]
hallo @legeidaa 

the issue is fixed in the version `5.0.2`.

Thanks!

**Comment by legeidaa** [comment]
i18n works now and i don't see any problems, thank you!
