### ISSUE TITLE
Some difficult questions (SCSS import as string)...

### ISSUE THREAD

**Issue by unit-404** [webdiscus/pug-plugin#108]
How to use `scss` as compiled, but inline string when import from JS?
`import styles from './index.scss?scss';`

Tried, but there is weird effect with additional loader (in result empty string, or error when no `css-loader`). 
```js
// use require when mjs
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

//
export default {
    resourceQuery: /scss/,
    type: 'asset/source',
    use: [{
        loader: 'postcss-loader',
        options: {
            postcssOptions: require("../config/postcss.config.cjs")
        }
    }, 'sass-loader']
};
```

Earlier here was an error problem concerning misrepresentation. 
`Error: Cannot 'resolveSync' because the fileSystem is not sync. Use 'resolve'!`
However, this is regarding `pug-loader`.

**Comment by unit-404** [comment]
(Added some tree info)

**Comment by unit-404** [comment]
Wait some time before I reopen issue.

**Comment by webdiscus** [comment]
Hello @unit-404,

You can't use the `type: 'asset/source'` for imported SCSS in JS to inline CSS. That will be not works.
You can inline CSS imported in JS using the [css.inline](https://github.com/webdiscus/html-bundler-webpack-plugin#option-css) option.

See the test use case [js-import-css-inline-css](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/js-import-css-inline-css).

**Comment by unit-404** [comment]
I just needs to make support of some web-components in runtime, such as `<template>` files in `.pug` format, with embedded compiled SCSS.

**Comment by webdiscus** [comment]
@unit-404 

can you please create small repo with your use case.

**Comment by webdiscus** [comment]
```diff
template.launcher.immersive
    .wrap
        .grid(part='inner')
            slot

    // webpackIgnore: true
    style(scoped='').
        @import url("./modules/uno.css");

    // webpackIgnore: true
    style(scoped='').
        @import url("./modules/styles.css");

    // exact moment, but in practice harder
-    style(scoped='')
-        include ./x-grid.scss
     //- you can inline a style using `?inline` query (no webpack configuration required)
          in generated HTML will be <style>... compiled CSS ...</style>
+    link(href='./x-grid.scss?inline' rel='stylesheet')
```

**Comment by unit-404** [comment]
I sometimes thought that <link> is still for the <head> tag, and is more intended for global styles, while <style> still implies `scoped` ie within the web component.

**Comment by webdiscus** [comment]
> I sometimes thought that `<link>` is still for the `<head>` tag, and is more intended for global styles, while `<style>` still implies `scoped` ie within the web component.

you can use link tag in Pug anywhere, not only in head, this is just a syntax that allow you to include CSS anywhere in your template:

```pug
template
  divcomponent
       link(href='./x-grid.scss?inline' rel='stylesheet' scope='some')
```

will be compiled to:

```html
<tremplate>
  <div class="component">
    <style scope="some">
      ... CSS ...
    </style>
  </div>
</tremplate>
```

**Comment by webdiscus** [comment]
@unit-404 

I have added experimental support to include a compiled CSS directly to `style` tag using the `require()` and the `?include` query:

```pug
style(scoped='some')=require('./x-grid.scss?include')
```

The generated HTML:

```html
<style scope="some">
    ... CSS ...
</style>
```

Please, update the plugin to the version `5.2.0`.
