### ISSUE TITLE
If HMR is disabled then page gets infinite reload

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/pug-plugin#22]
@webdiscus that is great!

The `infinite reload loop` is still there for me - now with both HMP Enabled/Disabled.

I noticed that if I open the `dev-tools (on browser)` it stops reloading and gives the following HMP warning(s) in the console.

![Screenshot 2022-06-19 at 8 48 50 AM](https://user-images.githubusercontent.com/36254505/174464593-3af054bb-a143-49f9-96e8-6a8bb38e9809.png)

Also I have added video below to see it live:

https://user-images.githubusercontent.com/36254505/174464638-7d7fc767-c3c3-42b5-a839-60b3bdd4eef0.mp4

_NOTE: If dev-tools are active then it works fine,  if dev-tools are not opened it gives this infinite loop behaviour on all the browsers._

My **devServer** config is as follow:

```
devServer: {
    devMiddleware: {
      publicPath: join(__dirname, 'build'),
      writeToDisk: true,
    },
    port: '9999',
    proxy: {
      '/': {
        target: `http://localhost/${projectName}/build`,
      },
    },
    static: {
      directory: join(__dirname, 'build'),
    },
    watchFiles: {
      paths: ['src/**/*.*'],
      options: {
        usePolling: true,
      },
    },
  },
```

Hope all this give you some direction in order to help this issue.

**Comment by webdiscus** [comment]
@kumardeepakxyz

thank you for video.
Sorry, I don't know your full setup and I can't start dev server with `devServer.proxy`.
Can you please create small repo, where I can simple run `npm run start` to reproduce the issue.

Try to disable the object `devMiddleware`, it's not needed if used `watchFiles` or disable `watchFiles`.

**Comment by kumardeepakxyz** [comment]
I'll try to do that with some dummy setup.

**Comment by webdiscus** [comment]
@kumardeepakxyz 

Import CSS/SCSS from `node_module` is very easy:
```scss
@use 'MODUE_NAME/path/to/style';
```

in your case:
```scss
@use '@splidejs/splide/src/css/core/index';
```

**Important:**  omit the file extension, e.g. .scss, .css
