### ISSUE TITLE
Can't resolve the file when using splitChunks

### ISSUE THREAD

**Issue by silveoj** [webdiscus/pug-plugin#25]
See branch https://github.com/silveoj/pug-plugin-responsive-loader-issue/tree/scss-and-chunks

I can't build if I use
```javascript
splitChunks: {
  chunks: 'all', // remove it to work
},
```

I get error on Win and Linux:
`Can't resolve the file ../src/assets/img/image.png in ..\src\html\pages\view-2.pug`
here: 
```pug
header
  img(src=require('~Images/image.png'))
```

- Also it starts to works SOMETIMES if I remove `.browserlistrc`
- I can replace `padding-bottom` to `padding-top` and it will work.
- I can remove random line and it CAN start to work.

I think it's `pug-plugin` issue because error with `require('~Images/image.png')`

To run webpack-dev-server I need to remove `require('~Images/image.png')`, run server and restore `require`. Now it's work on dev-server.
But there is no chance to build `dist` files

**Comment by webdiscus** [comment]
@silveoj thank you for the issue report.
I will fix it.

**Comment by webdiscus** [comment]
@silveoj 

I can't reproduce the issue.
See please the [PR](https://github.com/silveoj/pug-plugin-responsive-loader-issue/pull/1).

In your repo I have updated pug-plugin to v2.8.0 and added splitChunks. It's works on macOS.
Could you add the needed code to [repository] (https://github.com/silveoj/pug-plugin-responsive-loader-issue/tree/scss-and-chunks) to reproduce the issue.

P.S.  I will check it on Win10 yet.

**Comment by silveoj** [comment]
@webdiscus 
`main` branch works for me also.
See please `scss-and-chunks` branch. All packages are out of date.

**Comment by silveoj** [comment]
@webdiscus 
`main` branch works for me also.
See please `scss-and-chunks` branch. All packages are out of date.
Win10 / Ubuntu 18

**Comment by silveoj** [comment]
@webdiscus 
`main` branch works for me also.
See please `scss-and-chunks` branch. All packages are out of date.
Win10 / Ubuntu 20

**Comment by webdiscus** [comment]
@silveoj ah, sorry, I will get the scss-and-chunks branch.

**Comment by webdiscus** [comment]
@silveoj 

As temporary solution disable the postcssOptions by `postcss-loader` and it's works with splitChunks.
Seems, the postcss-loader breaks CSS standard syntax.  I will add supports for this case.

**Comment by webdiscus** [comment]
@silveoj 

The problem was by Webpack `splitChunks`. It's not a bug of pug-plugin.
Webpack splits all JavaScript files and those that not should, that completely breaks the compilation process.
I have some improvements in v2.9.3, update please the pug-plugin.

### Solution
You must concrete specify what scripts should be splitted, using optimization.splitChunks.cacheGroups:

```js
module.exports = {
  optimization: {
    splitChunks: {
      cacheGroups: {
        scripts: {
          test: /\\.(js|ts)$/,
          chunks: 'all',
        },
      },
    },
  },
  // ...
};
```

Note: in the `test` option must be specified all extensions of scripts which should be splitted.

**Comment by webdiscus** [comment]
@silveoj see the [PR](https://github.com/silveoj/pug-plugin-responsive-loader-issue/pull/2/), it works now.
