### ISSUE TITLE
When pug template is broken, error page is not properly rendered.

### ISSUE THREAD

**Issue by rrundzans** [webdiscus/pug-plugin#26]
Based on hello world example project.
I introduce error in about/index.pug template.
When opening /about.html unreadable page is returned to user.
Weirdly, when opening other valid page, like /contact.html, error is still displayed, and it is readable.
See screenshots.
I think, we should get readable error when opening broken page (/about.html).
Ideally we could also open valid pages, even if few others are broken.

![when-opening-broken-page](https://user-images.githubusercontent.com/1911658/176928645-345288d4-be5d-4006-9b97-ce8a1270d827.png)

![when-opening-other-page](https://user-images.githubusercontent.com/1911658/176928665-d472a1e9-a36c-463f-ac48-7c21d5342488.png)

**Comment by rrundzans** [comment]
Thank you! Keep up the good work.

**Comment by webdiscus** [comment]
@rrundzans 

Please, update the pug-plugin to v2.9.0.
Now on the broken page works auto-reload and an error is displayed.

P.S. an error message on "valid page" can be closed (click on X, at top right). This modal popup is generated by Webpack automatically.

**Comment by rrundzans** [comment]
@webdiscus Thanks for your quick action.
However, now I encounter Cannot find module '@babel/core/lib/vendor/import-meta-resolve' for my project. Same happens with hello-world app (fresh pull from pug-plugin master branch).

```
$ rm -rf node_modules/ yarn.lock
$ yarn
$ yarn run build
```

> ERROR in ./src/views/pages/about/index.pug
> Module build failed (from ./node_modules/@webdiscus/pug-loader/src/index.js):
> Error: Cannot find module '@babel/core/lib/vendor/import-meta-resolve'
> Require stack:
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/@webdiscus/pug-loader/src/index.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/loader-runner/lib/loadLoader.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/loader-runner/lib/LoaderRunner.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack/lib/NormalModuleFactory.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack/lib/Compiler.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack/lib/webpack.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack/lib/index.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack-cli/lib/webpack-cli.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack-cli/lib/bootstrap.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack-cli/bin/cli.js
> - /home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/webpack/bin/webpack.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:101:18)
>     at Object.<anonymous> (/home/ritvars/code/explore/pug-plugin/examples/hello-world/node_modules/@webdiscus/pug-loader/src/index.js:18:16)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at Module.require (internal/modules/cjs/loader.js:974:19)

Am I doing something wrong? Thanks.

**Comment by rrundzans** [comment]
@webdiscus I commented out offending (and apparently unused) require and it started to work again.
`const { re } = require('@babel/core/lib/vendor/import-meta-resolve');`
See: https://github.com/webdiscus/pug-loader/pull/20

**Comment by webdiscus** [comment]
> const { re } = require('@babel/core/lib/vendor/import-meta-resolve');

Ah, sorry! My IDE automatically added this wrong module when I used absolutely other resolver. I'll fix that right away.

**Comment by webdiscus** [comment]
@rrundzans 

The fixed version is 2.9.1.

Thank you!

**Comment by rrundzans** [comment]
Thanks a lot! It now works.👍 
I discovered another issue - hmr.js inclusion is not working when in Windows. I can fix it like this:
https://github.com/rrundzans/pug-loader/commit/29cd3bd123e573ab24bd4306b5c0304ab88ef3f3
I am not sure this is not breaking other things, thus no PR.

**Comment by webdiscus** [comment]
@rrundzans 

thanks for issue report.
In v2.9.2 is fixed issue with HMR on Windows.

P.S. your solution works on Windows only. In the v2.9.2 is common solution for both Linux and Windows.

**Comment by betmenslido** [comment]
Big thanks! I checked and all seems to be fine.

> Note: in webpack.config.js from the examples, on Windows you need to change all include parameters, for example include: /assets\/images/ to Windows format.

Thanks for the heads up. I fixed it already with, should work both on Windows and Linux:
`include: /assets(\/|\\)images/`

**Comment by rrundzans** [comment]
@webdiscus

Big thanks! I checked and all seems to be fine.

Note: in webpack.config.js from the examples, on Windows you need to change all include parameters, for example include: /assets/images/ to Windows format.

Thanks for the heads up. I fixed it already with, should work both on Windows and Linux:
include: /assets(\/|\\)images/
