### ISSUE TITLE
Mixin doesn't generate slash for self closing tags

### ISSUE THREAD

**Issue by silveoj** [webdiscus/pug-plugin#28]
I prepared 2 branches:
- works with pure-pug [self-closing-outer-mixin-pure-pug](https://github.com/silveoj/pug-plugin-responsive-loader-issue/tree/self-closing-outer-mixin-pure-pug)
- doesn't work with pug-plugin [self-closing-outer-mixin](https://github.com/silveoj/pug-plugin-responsive-loader-issue/tree/self-closing-outer-mixin)

I use `doctype html5` to pug adds me slash for self closing tags.

2 test cases:
1. works - when I use markup without mixin output generates slash for self closing tags
2. doesn't work - when I use markup inside any mixin (mixin is placed inside/outside of files) output doesn't generate slash for self closing tags: `source`, `img`, `link`, etc

**Actual**:
```
<link rel="stylesheet" href="/styles.css">
<source srcset="/assets/img/image.png" type="image/png">
<img src="/assets/img/image.jpeg" alt="description">
```

**Expected**:
```
<link rel="stylesheet" href="/styles.css"/>
<source srcset="/assets/img/image.png" type="image/png"/>
<img src="/assets/img/image.jpeg" alt="description" />
```

Quick fix: add slash at the end of pug tag - `img(src="..")/`

**Input**
```pug
mixin my-picture
  picture
    source(
      srcset=require(`/assets/img/image.png`)
      type='image/png'
    )
    img(
      src=require(`/assets/img/image.jpeg`)
      alt=''
    )

doctype html5
html
  body
    h2 picture + img - mixin
    h3 doesn't work
    +my-picture
```
**~Output**
```html
    <picture>
      <source srcset="/assets/img/image.0acbc4558e7b27c288531b5c4f5971c7-737w.png" type="image/png">
      <img src="/assets/img/image.a222788447658269ca708d9ab19798a6-737w.jpeg" alt="">
```

**Comment by webdiscus** [comment]
@silveoj 

I have checked your [self-closing-outer-mixin](https://github.com/silveoj/pug-plugin-responsive-loader-issue/tree/self-closing-outer-mixin) repo.

All works fine exact as you wish, if you change the _index.pug_:
```pug
doctype html5 <-- add exact `html5` for self closing tags with '/' at end.
html <-- add html tag as ROOT tag for `head` and `body`
  head
  ...
  body
  ...
```

Build `dist`
```
npm run build:prod
```

Generated `dist/index.html`
```html
<!DOCTYPE html5>
<html>
  <head>
    <link rel="stylesheet" href="/assets/css/styles.fc84a125.css" />
  </head>
  <body>
    <header>Index</header><img src="/assets/img/image.0acbc4558e7b27c288531b5c4f5971c7-737w.png" /><img
      src="/assets/img/image.0acbc4558e7b27c288531b5c4f5971c7-737w.png" />
    <picture>
      <source type="image/webp" /><img src="/assets/img/image.a222788447658269ca708d9ab19798a6-737w.jpg"
        srcSet="/assets/img/image.3116ea8cbe292efb5c9006fd5253304f-480w.jpg 480w,/assets/img/image.0f4250fbe195dd8e4ca05b0cbdf13961-640w.jpg 640w,/assets/img/image.a222788447658269ca708d9ab19798a6-737w.jpg 800w"
        width="737" height="365" />
    </picture>
    <script src="/assets/js/main.142c51db.js"></script>
  </body>
</html>
```

> Note: to generate formatted HTML, add to PugPlugin the `pretty: true` option.

**Comment by webdiscus** [comment]
@silveoj why you need legacy XHTML syntax with `/` for self-closing tags? Today it is not recommended to use.
W3C recommend to use the `<!DOCTYPE html>`, which is without `/` for self-closing tags, e.g.: `<img src="image.png">`.

**Comment by webdiscus** [comment]
@silveoj 
yes, I can reproduce the issue with missing `/>`, using mixin.

**Comment by webdiscus** [comment]
@silveoj 

I found the problem!

In the original [pugjs/pug-loader](https://github.com/pugjs/pug-loader/blob/99e7e1240e312d735f8de3e40e70ca5adb6ace7d/index.js#L138) the default value of the `doctype` option is `html`.

```js
doctype: query.doctype || "html",
```

But, in the `pug-cli`, the default `doctype` is `undefined`.

It means, that if you want use custom doctype in Pug, then must be defined the pug-loader option `doctype` too.

Here is the dilemma:

1. in my Pug loader set default `doctype` as `undefined`. It's BREAKING CHANGE and will be not compatible with original pug-loader. I prefer to keep compatibility.
2. stay as by original pug-loader. Then you must define the `doctype` option by pug-loader self.


## Working solution

Pug template:
```pug
mixin img
  img(src='image1.png')

doctype html5
html
  body
    +img
    img(src='image2.png')
```

Webpack config:
```js
const PugPlugin = require('pug-plugin');
module.exports = {
 // ...
  module: {
    rules: [
      {
        test: /\.pug$/,
        loader: PugPlugin.loader,
        options: {
          doctype: 'html5', // <-- add this option
        },
      },
    ],
  },
};
```

Will be generate:
```html
<!DOCTYPE html5><html><body><img src="image1.png"/><img src="image2.png"/></body></html>
```
