### ISSUE TITLE
How to minify inline JS & CSS & Generate Hash?

### ISSUE THREAD

**Issue by kumardeepakxyz** [webdiscus/pug-plugin#29]
Hi @webdiscus 

1. I am not able to minify inline JS & CSS.
2. Can i generate Hash for `script` & `link` tags?

Before `pug-plugin` i used `HtmlWebpackPlugin` to do the same.

Sample Code:
```js
new HtmlWebpackPlugin({
    template: join(__dirname, 'xyz.pug'),
    filename: 'xyz.html',
    hash: true,
    minify: {
      minifyCSS: true,
      minifyJS: true,
  },
}),
```

```js
hash: true
// this appends a unique webpack compilation hash
// to all included scripts and CSS files
```

```js
minify: {
    minifyCSS: true,
    minifyJS: true,
}
// this minified the inline css and js
```

**Comment by webdiscus** [comment]
Hi @kumardeepakxyz,

1. no. Inline CSS/JS is a pure text and will be not analysed by Webpack.
2. Yes of course. It's the feature of `pug-plugin`. Did you read the [README.md](https://github.com/webdiscus/pug-plugin)?

Use `require()` in Pug for styles and scripts:
```pug
link(href=require('./styles.scss') rel='stylesheet')
script(src=require('./main.js'))
```

Generated HTML contains hashed CSS and JS output filenames:
```html
<link href="/assets/css/styles.05e4dd86.css" rel="stylesheet">
<script src="/assets/js/main.f4b855d8.js"></script>
```

**Comment by kumardeepakxyz** [comment]
@webdiscus 

1. my point is why can't `pug-plugin` minify CSS and JS in PUG file as `HtmlWebpackPlugin` does.
2. I am not referring to the **name hash**, however **hash** that gets added at the end of the filename for cache busting.

```html
<script defer="defer" src="assets/js/45a02863ac123a4b44e3.js?1d89f17884ba249ed0be"></script>
<link href="assets/css/b78c8253ad053fd6fc27.css?1d89f17884ba249ed0be" rel="stylesheet">
// the "1d89f17884ba249ed0be" part in both tags after ? mark
```

**Comment by webdiscus** [comment]
1. inline CSS/JS is **bad practice** and for _special case_ should be used  1-2 `inline` code lines. All CSS and JS code must be in separate files. It will be never released, because it does not make a sense.

**Comment by webdiscus** [comment]
2. I don't understand why you don't like the hashed filename?

**Comment by kumardeepakxyz** [comment]
> 1. inline CSS/JS is **bad practice** and for _special case_ should be used  1-2 `inline` code lines. All CSS and JS code must be in separate files. It will be never released, because it does not make a sense.

@webdiscus 

I agree with you about in inline css/js is bad.

Sometimes I just add, say GTag in footer/header of pug file and want that line of code to be minified in the html output. I many time don't feel necessary to add GTag or something similar to a separate JS file.

Hence if pug-plugin can minify the code between script tags defined in pug template that would be useful.

If not, I am already using HTMLWepackPlugin that just works fine in this case.

🙏😇

**Comment by kumardeepakxyz** [comment]
> 2. I don't understand why you don't like the hashed filename? It's standard de facto.
> 
> 
> 
> For JS and CSS you can define contenthash as query param.
> 
> 
> 
> For JS use `filename` option in `output`:
> 
> ```js
> 
> filename: 'assets/js/[name].js?[contenthash:8]',
> 
> ```
> 
> 
> 
> For CSS use `filename` option in `extractCss` module:
> 
> ```js
> 
> filename: 'assets/css/[name].css?[contenthash:8]',
> 
> ```
> 
> 
> 
> Each file will be with own hash.
> 
> 
> 
> If you want one 'hash' for all js/css then you can self generate in Webpack config a timestamp and add it to filename in function:
> 
> 
> 
> ```js
> 
> const tstamp = 1234567890;
> 
> ...
> 
> 
> 
> // use filename as function for JS and CSS, like following:
> 
> filename: (pathData) => `assets/css/${pathData.chunk.name}.css?${tstamp}`
> 
> ```
> 
> 

I will try it this way. Thank you 🙏🤩

**Comment by kumardeepakxyz** [comment]
> 1. inline CSS/JS is **bad practice** and for _special case_ should be used  1-2 `inline` code lines. All CSS and JS code must be in separate files. It will be never released, because it does not make a sense.

As an example:

**For PUG**

```pug
doctype html
html(lang="en")
  head
    meta(charset="UTF-8")
    meta(http-equiv="X-UA-Compatible", content="IE=edge")
    meta(name="viewport", content="width=device-width, initial-scale=1.0")
    title Document

    script(async src='https://www.googletagmanager.com/gtag/js?id=AW-xxxxxxxxx')
    script.
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      gtag('config', 'AW-xxxxxxxxx');

  body 
    h1 test
    p Lorem ipsum dolor sit amet consectetur adipisicing elit.
```

**Rendered Output is**
```html
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><script async src="https://www.googletagmanager.com/gtag/js?id=AW-xxxxxxxxx"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());
  gtag('config', 'AW-xxxxxxxxx');
</script></head><body><h1>test</h1><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p></body></html>
```

**---HOWEVER---**

**Expected Output is**
```html
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><script async src="https://www.googletagmanager.com/gtag/js?id=AW-xxxxxxxxx"></script><script>window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'AW-xxxxxxxxx'); </script></head><body><h1>test</h1><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p></body></html>
```

**CODE INSIDE SCRIPT TAG MUST BE MINIFIED**

**Comment by webdiscus** [comment]
@kumardeepakxyz 

Minification of inline code is not a task for the pug-plugin.
If you wish to minify something in Pug, you can do it self, very easy.

1. add to the `filters` option  of `PugPlugin.loader` the custom `minify` filter:
```js
{
  test: /\.pug$/,
  loader: PugPlugin.loader,
  options: {
    filters: {
      minify: (content) => content.replace(/\n/g, ''), // <-- here you can use any external lib to minify
    },
  }
},
```

2. use your custom `:minify` filter in Pug code:
```pug
doctype html
html(lang="en")
  head
    script(async src='https://www.googletagmanager.com/gtag/js?id=AW-xxxxxxxxx')
    script: :minify
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      gtag('config', 'AW-xxxxxxxxx');

  body
    h1 Hello World!
```

> Note: after the filter `:minify` the dot `.` not required.

3. will be generate minified inline code
```html
<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=AW-xxxxxxxxx"></script><script>window.dataLayer = window.dataLayer || [];function gtag() {  dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'AW-xxxxxxxxx');</script></head><body><h1>Hello World!</h1></body></html>
```

**Comment by kumardeepakxyz** [comment]
that I have tried, but I was thinking if it could be just an `option` argument in `pug-plugin`.

anyhow thank you for the answer. 😇

**Comment by webdiscus** [comment]
no, no, "they are two different pairs of shoes" ;-)

The pug-plugin get already compiled HTML code from integrated pug-loader and can't analyse HTML to minify everything.
The `HtmlWebpackPlugin` parse received HTML code, analyse and minify a code blocks. But it is very too slow process.

Pug plugin is much faster because all processes are optimised and will be applied just at right stage.
Also, the minification of inline code must be processed by pug-loader. It is right, it is fast, it is logic.

Webpack has `plugins` and `loaders`. Each type of module performs its own tasks.
