### ISSUE TITLE
Automatic "publicPath"

### ISSUE THREAD

**Issue by kumardeepakxyz** [webdiscus/pug-plugin#31]
Why is `output.publicPath: 'auto'` not supported?

When are you planning to role this feature?

![Screenshot 2022-07-10 at 10 22 55 AM](https://user-images.githubusercontent.com/36254505/178131815-34e9bf6a-1cfa-4659-bc70-9c936cec30e2.png)

**Comment by webdiscus** [comment]
@kumardeepakxyz 

> Why is output.publicPath: 'auto' not supported?
Because `auto` value is a "black magic" and is very complex to implement. I don't known any usage case for `auto`.
It will be never released, because `it has no sense`.

**Comment by kumardeepakxyz** [comment]
okay,

So how can I resolve the problem of 404 when deploying the website to a sub directory with `output.publicPath = '/'` 

`output.publicPath = '/'` meaning it can find the files in the server root, so when website is on the **root** everything is fine, but once its moved to a sub directory, its link to css, js, images etc. are broken as they still refer to the server root.

I have tried
`output.publicPath = ''` - it fails to load SCSS URL Images
`output.publicPath = './'` - it also fails to load SCSS URL Images

*OUTPUT OF URL RESOLVE*
`/path/to/assets...`

*EXPECTED OUTPUT*
`path/to/assets...`
`/` should be somehow eliminated.
