### ISSUE TITLE
Can't Resolve

### ISSUE THREAD

**Issue by yashiel** [webdiscus/pug-plugin#34]
After the new update, previously resolved SCSS paths can't resolve now, everything is breaking. All settings are clear and properly configed

https://i.imgur.com/a1Ktwn1.png

**Comment by yashiel** [comment]
NVM fixed the issue.

**Comment by webdiscus** [comment]
> NVM fixed the issue.

What version of node was used that caused the issue?
What version of node are you using now?

**Comment by yashiel** [comment]
All the latest and greatest. It's all my mistakes. I merged renovate PR, made small changes according to your updated methods, but forget to rerun yarn install. Stupid me. Lol. Everything is work perfectly. Thanks for building this. I'm using this in my enterprise application frontend, everyone happy about the overall process and flexibility

**Comment by yashiel** [comment]
Node v17.3.0
NPM 8.3.0

**Comment by webdiscus** [comment]
> I'm using this in my enterprise application frontend, everyone happy about the overall process and flexibility

Thank You for usage!

**Comment by silveoj** [comment]
@webdiscus

`script(src=require('/js/main.js'))`:
- `3.0.1` - works
- `3.1.0` - doesn't work: `Cannot find module '/js/main.js'`

With styles is ok: `link(href=require('/styles/styles.scss'), rel='stylesheet')`

Structure:
- `src/views/index.pug`
- `src/js/main.js`
- `src/styles/styles.scss`
