### ISSUE TITLE
Bootstrap JS not executing after build

### ISSUE THREAD

**Issue by yashiel** [webdiscus/pug-plugin#35]
I just noticed, when i in the development mode, bootstrapjs work perfectly fine, but once I build it, paths going to extract and include in the head area, but none of the functions are working tried all possible ways, but none of them are working,

try to include like this

```
script(src=require('../../../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'), defer=true) 
script(src=require('./onboarding.js'), defer=true) 

```

and then this one inside onboarding.js

```
import "bootstrap";
```

also tried
```
require("bootstrap")
```

all of them are working but not after build js files going to compile and include in the head area.

**Comment by yashiel** [comment]
I tried it nothing happened, even console not throwing any errors, that's the issue. When I run dev mode it's working fine when i run build bootstrap link there with the all the JavaScript but none of them are running or throwing any errors:

before build (yarn watch) 

https://imgur.com/6jS8cGZ

after build (yarn build)

https://imgur.com/DrX1Uzj

**Comment by webdiscus** [comment]
@yashiel 

can you please create small repo with reproducible issue?

**Comment by yashiel** [comment]
try this 

https://github.com/yashiel/testrepo

these are the areas with dropdown

https://i.imgur.com/amB4UTC.png

goto /onboarding_1.html

**Comment by webdiscus** [comment]
@yashiel 

v3.1.1 with many bugfixes is released!
Please see my comments in the [PR](https://github.com/yashiel/testrepo/pull/9).
You have wrong `webpack.prod.js` therefore `npm run build` not works. I have fixed your config in PR.

**Comment by yashiel** [comment]
I've noticed your changes, and I implement those changes to my original production ready code, everything is running smoothly without any issue, my other bug also fixed, 

I have to tweak purge CSS to solve that issue like you mentioned, thanks anyway. I'll close this thread now.
