### ISSUE TITLE
[BUG on Windows] Unexpected warnings and errors in v3.1.0

### ISSUE THREAD

**Issue by yashiel** [webdiscus/pug-plugin#37]
Hi,
this issue came today after updated to the newest version, now it shows warning message continuously  and breaks previously worked and linked script paths. It keeps saying that I need to avoid importing styles and JS directly inside entryjs files. But I don't have any JS or styles define inside entry JS file.

Screenshot
https://i.imgur.com/hBVNFWG.png

**Comment by webdiscus** [comment]
@yashiel 

Thanks for bug reporting.
Can you please create small reproducible repo? Perhaps you have special use case which is for `pug-plugin` yet unknown.

**Comment by yashiel** [comment]
I just revert back to previous version, everything is working as intended and smoothly, the new version has some issues i guess

**Comment by yashiel** [comment]
https://github.com/yashiel/testrepo

I have updated this test repo, same issue happened in this repo also. You can try.

**Comment by webdiscus** [comment]
@yashiel 

Thank You very much!

**Comment by yashiel** [comment]
https://i.imgur.com/Olgys6a.png

**Comment by webdiscus** [comment]
@yashiel 

v3.1.1 with many bugfixes is released!
Please see my comments in the [PR](https://github.com/yashiel/testrepo/pull/9).
You have wrong `webpack.prod.js` therefore `npm run build` not works. I have fixed your config in PR.

**Comment by yashiel** [comment]
This issue solve at version v3.1.1 everything is running smoothly. Thanks

**Comment by perry-mitchell** [comment]
That test repo isn't up anymore.. Can the solution be shared here by any chance? I'm having the same issue:

![image](https://user-images.githubusercontent.com/3869469/187616046-7df5e3e9-fbbd-4f5b-9d01-bfa3a091278c.png)

@webdiscus @yashiel
