### ISSUE TITLE
Windows only: All reported dependencies need to be absolute paths.

### ISSUE THREAD

**Issue by Mizan-Rifat** [webdiscus/pug-plugin#5]
[NOTE] The issue has relation with the [issue in pug-loader](https://github.com/webdiscus/pug-loader/issues/12).

### Original description

When I try to include a partial mixin file it shows:

`Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).      
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.`

Why is this happening? I have tried `./Stats` and `src/pug/Stats` but it shows the same error...
And also webpack dev server is not watching the partials file. On edit, the server is not refreshing...

**Comment by webdiscus** [comment]
Hello @Mizan-Rifat ,

do you can please create a simple repo with reproducible issue.
I need to see the webpack.config.js and pug templates.

**Comment by webdiscus** [comment]
The webpack dev server watch and render all pug files, but auto refresh work for pug templates included in JavaScript only. All static rendered templates (defined in entry) will be new generate but not auto refreshed. Refresh you browser manually.

Auto refresh for static templates will be never realised, because it is very complex and it's not worth it.

**Comment by Mizan-Rifat** [comment]
@webdiscus  https://github.com/Mizan-Rifat/pug-plugin-demo here is a simple repo..
Here if you change in `src/pug/starter.pug` and refresh the page, you will see the change. But if you change in `src/pug/mixins/Starter.pug` and refresh the page you will not see the change...
Open the terminal you will see ` All reported dependencies need to be absolute paths.` error.
And I'm using windows os...

**Comment by webdiscus** [comment]
@Mizan-Rifat yes, I can reproduce the issue.

**Comment by webdiscus** [comment]
@Mizan-Rifat Is the problem solved for you?
