### ISSUE TITLE
[Windows] Inline CSS not working due to the difference between sourceRequest and rawRequest

### ISSUE THREAD

**Issue by YUCLing** [webdiscus/pug-plugin#56]
I'm trying to use inline CSS with the plugin, but what i got inside `style` is the resource url of the SCSS I required.

For example, if I use inline CSS using `style=require('./styles.scss?inline')`, the content of `style` will be `style.3ef5f.css` instead of the CSS code generated by webpack.

After some research, I found that the `sourceRequest` ([index.js#L655](https://github.com/webdiscus/pug-plugin/blob/0a2cd56a336ac9dc74613be30ac93dbfb15aeaa5/src/index.js#L655)) added to `AssetSource` is different from `rawRequest` ([Resolver.js#L286](https://github.com/webdiscus/pug-plugin/blob/0a2cd56a336ac9dc74613be30ac93dbfb15aeaa5/src/Resolver.js#L286)) used by `require`.  
The `sourceRequest`'s path separator is `\`, which is Windows style (I'm working on Windows).  
The `rawRequest`'s path separator is `/`.  
If I replace all `/` in `rawRequest` to `\` using debugger, everything is working as expected.

**Comment by webdiscus** [comment]
Hello @YUCLing,

thank you for the issue report.
I will try to fix it.

**Comment by webdiscus** [comment]
@YUCLing 

the bug is fixed in `v4.9.0`, please  update the package.

P.S. in `v.4.9.0` is added supports for inline JS, see [How to inline JS in HTML](https://github.com/webdiscus/pug-plugin#recipe-inline-js)

**Comment by YUCLing** [comment]
Confirmed it's fixed.

But your inline JS seems to be not working properly. I'm not sure what caused it, I will try to find out when possible and open an new issue if necessary.  
The following output is what I got from inline JS.

```pug
script=require("../test/config.ts?inline")
```
Outputs
```html
<script>
  I: /path-to-project/test / config.ts
</script>
```

**Comment by webdiscus** [comment]
@YUCLing 

I have the [inline script test](https://github.com/webdiscus/pug-plugin/tree/master/test/cases/inline-script-query). It's work.
You can do your own test based on my test to reproduce the issue.

P.S. yes, create please new issue for inline script.
