### ISSUE TITLE
How to combine all CSS and JS files in bundle?

### ISSUE THREAD

**Issue by dimau** [webdiscus/pug-plugin#63]
Hi guys,

Maybe I missed something. But how to combine all css files for the page in one bundle css file? 
The same for js files - how to combine all js files for the page in one bundle? 

Because I construct my pages in pug including widgets (also in pug), each widget has its own styles and scripts. I would like to gather all styles all widgets in one css file for the page, and I can't find any information on it in pug-plugin documentation...

**Comment by webdiscus** [comment]
Hi @dimau,

you should self create a bundle for each page. This is not the task of the plugin.

For example, there a page with many styles:

```
./src/views/pages/home/
- style1.scss
- style2.scss
- vendor.css
- main.scss // <= add one bundle file pro page
```

Create the `main.scss` pro page to bundle all your SCSS/CSS in one file:
_main.scss_
```scss
@use './style1.scss';
@use './style2.scss';
@use './vendor.css';
```
Now you can load only one `main.scss` file  in a Pug template.

Similarly you can do for JS.

**Comment by dimau** [comment]
Ok, thank you for the quick response!
