### ISSUE TITLE
Images are broken after build

### ISSUE THREAD

**Issue by a-gunderin** [webdiscus/pug-plugin#68]
Hello team.
For some reason images are broken after build (jpg, png and webp; svgs are fine).
Repo: https://github.com/a-gunderin/webpack-starter
I'm not sure that this issue connected with pug-plugin.
But I could not find a solution to this issue anywhere.
I would be grateful if you could tell me what the trick is.
Regards.

**Comment by webdiscus** [comment]
Hello @a-gunderin,

thanks for the issue report.
I will research the problem.

**Comment by webdiscus** [comment]
@a-gunderin 

The  pug-plugin doesn't touch images, it replaces the source filename with the output filename.

The strange atomizer-plugins does not work accurately and the image content is duplicated in the image file.
If you disable the atomizer, then images are generated correctly.

**Comment by webdiscus** [comment]
@a-gunderin 

This is the `atomizer-plugins` bug. This plugin brake the binary images, but SVG is ok.
Please create issuer ticket by the atomizer-plugin.

Here is the [PR](https://github.com/a-gunderin/webpack-starter/pull/1) with reproducible issue.
No pug-plugin, pure JS + import an image => output image is broken.

**Comment by a-gunderin** [comment]
Many thanks!
