### ISSUE TITLE
[FEATURE REQUEST] Preload support for font image audio video

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/pug-plugin#69]
Here is the modified FR #60.

Automatically preload assets resolved in HTML or in CSS:
- style
- script
- font
- image
- audio
- video

For example, there is the style used a font:

_style.css_
```css
@font-face {
  font-family: "Fira Sans";
  src:  url('fonts/fira/FiraSans-Regular.woff2') format('woff2');
}
```

The generated HTML:
```html
<html>
<head>
  <title>Demo</title>

  <!-- injected preloads -->
  <link rel="preload" href="css/style.1f4faaff.css" as="style">
  <link rel="preload" href="js/main.c608b1cd.js" as="script">  
  <link rel="preload" href="fonts/fira/FiraSans-Regular.woff2" as="font" type="font/woff2" />
  <link rel="preload" href="assets/img/imac.3666c92d.svg" as="image" type="image/svg+xml">
   
  <!-- load style -->   
  <link href="style.1f4faaff.css" rel="stylesheet" />
</head>
<body>
  <img src="assets/img/apple.3666c92d.svg" alt="apple">
  ...
  <!-- load script -->
  <script src="js/main.c608b1cd.js"></script>
</body>
</html>
```

The auto generated preload `link` tag should be injected before a first `style` or `script` tag in `head`.

The option name should be `preload`:

```js
{
  preload: [
    {
      test: /\.(s?css|less)$/,
      as: 'style',
    },
    {
      test: /\.(js|ts)$/,
      as: 'script',
    },
    {
      test: /[\\/]fonts[\\/].+(eot|ttf|woff|woff2)$/,
      as: 'font',
      // the `type` attribute will be added automatically : 'font/woff2',  'font/ttf', etc.
      // additional optional attributes 
      attributes: { crossorigin: true },
    },
    {
      test: /[\\/]images[\\/].+(svg|png|jpg)$/,
      as: 'image',
      // the `type` attribute will be added automatically : 'image/svg+xml',  'image/png', etc.
    },
  ],
}
```

**Comment by ladown** [comment]
Seems to be good. 

Going back to our last conversation about preload, do you think it might still be worth thinking about how scripts/styles could be captured through these settings? I thought about it to make the code more uniform. It looks strange when we specify preload for styles or scripts manually, and the plugin handles all our other assets

**Comment by webdiscus** [comment]
@ladown 

The plugin does not capture scripts/styles, because they already must be manual specified in HTML and not anywhere.
This is the goal this plugin: manually specify source scripts/styles directly in HTML.
This plugin don't inject the link/script tags.

P.S. You are probably confusing with another html-webpack-plugin that catches styles/scripts defined in Webpack config and then inserts them into HTML.

**Comment by webdiscus** [comment]
Preloading of scripts and styles will also be implemented too.

**Comment by webdiscus** [comment]
@ladown 

the new pug plugin `v5.0.0` is based on the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) and has all features, including the [preload](https://github.com/webdiscus/html-bundler-webpack-plugin#option-preload)
