### ISSUE TITLE
 How to use Tailwind CSS with pug-plugin

### ISSUE THREAD

**Issue by a-gunderin** [webdiscus/pug-plugin#73]
Hello @webdiscus !

I was trying to use Tailwind (https://github.com/tailwindlabs/tailwindcss) with pug-plugin but unfortunately I couldn't get the correct CSS to be generated.
Have you ever try to use Tailwind with pug-plugin?
Repo to reproduce: https://github.com/a-gunderin/webpack-starter

Regards.

**Comment by a-gunderin** [comment]
Thanks a lot for so quick response.
I was trying to use some approaches and tips from [this issue](https://github.com/webdiscus/pug-loader/issues/13) but unfortunately no results =(

**Comment by webdiscus** [comment]
@a-gunderin,

Tailwindcss works fine!

I found a solution, just one moment, I push it in your repo.

**Comment by a-gunderin** [comment]
Many thanks for your help!
For those who will be looking for a solution to this issue:
```
tailwind don't works with "type": "module", but in cjs mode works fine!
```

**Comment by webdiscus** [comment]
Hi @a-gunderin,

tailwind don't works with `"type": "module"`, but in `CommonJS` mode works fine! 
The problem is that in `ESM` mode, `postcss-loader` does not run the `tailwindcss` plugin.

I don't know why.

# The solution for everyone who reads it in the future.

Install the packages as dev dependencies:
```
"css-loader": "^6.7.3",
"postcss": "^8.4.21",
"postcss-loader": "^7.1.0",
"postcss-preset-env": "^8.0.1",
"pug-plugin": "^4.9.7",
"tailwindcss": "^3.2.7",
"webpack": "^5.76.2",
"webpack-cli": "^5.0.1",
"webpack-dev-server": "^4.13.1"
```

Create the `postcss.config.js`:
```js
module.exports = {
  plugins: [
    'postcss-preset-env',
    'tailwindcss',
  ],
};
```

Create the `tailwind.config.js`:
```js
module.exports = {
  content: [
    './src/views/**/*.pug', // path to Pug templates
  ],
};
```

Create the Webpack config:
```js
const path = require('path');
const PugPlugin = require('pug-plugin');

module.exports = {
  entry: {
    index: './src/views/pages/index.pug',
  },

  output: {
    path: path.join(__dirname, 'dist'),
  },

  plugins: [
    new PugPlugin({
      js: {
        filename: 'js/[name].[contenthash:8].js',
      },
      css: {
        filename: 'css/[name][contenthash:8].css]',
      },
    }),
  ],

  module: {
    rules: [
      {
        test: /\.pug$/,
        loader: PugPlugin.loader,
      },
      {
        test: /\.css$/,
        use: ['css-loader', 'postcss-loader'], // add postcss-loader
      },
      {
        test: /\.(png|jpe?g|webp|gif)$/i,
        type: 'asset/resource',
        generator: {
          filename: 'images/[name].[hash:8][ext]',
        },
      },
    ],
  },
};
```

Using these configs, Tailwind CSS works fine with pug-plugin!
