### ISSUE TITLE
Unexpected token '.' in Plugin.js issue. Can't compile my files

### ISSUE THREAD

**Issue by apeplusplus** [webdiscus/pug-plugin#74]
Hello! I'm stuck with the error while trying to compile my files with pug-plugin
The error looks like this. There I tried to compile the example from your repo

![image](https://user-images.githubusercontent.com/130275430/232393239-d46b8c57-1f72-4de9-84e0-f1a22374eb38.png)

**Comment by webdiscus** [comment]
Hi @apeplusplus 

since version 3.x plugin works with node 14+.
Please update you node version or use the plugin version `2.9.3` (last version supported node 12).

> **Warning**
>
> Node 12 is End-of-Life.
