### ISSUE TITLE
When connecting one page to js, ​​a number is substituted

### ISSUE THREAD

**Issue by exocornet** [webdiscus/pug-plugin#75]
How to make sure that this number does not exist?

![index](https://user-images.githubusercontent.com/57918887/234977869-26f8dd66-cbb4-4cee-8cf9-e86d11bc1889.png)

**Comment by webdiscus** [comment]
Hello @exocornet,

due to inner processing of assets with the same name will be add an index, because Webpack entry is the object with unique keys, otherwise Webpack generate an Error.

To avoid indexing, just use different names for pages, styles and scripts.
For example:

instead of:
- index.html
- index.scss
- index.js

use the different naming:
- index.html
- app.js
- main.scss

**Comment by exocornet** [comment]
> Hello @exocornet,
> 
> due to inner processing of assets with the same name will be added an index, because Webpack entry is the object with unique keys, otherwise Webpack generate an Error.
> 
> To avoid indexing, just use different names for pages, styles and scripts. For example:
> 
> instead of:
> 
> * index.html
> * index.scss
> * index.js
> 
> use the different naming:
> 
> * index.html
> * app.js
> * main.scss

Hello. And if I have several pages and I need, for example, to connect my own js to each page. Which, in principle, your plpgin does conveniently. At the same time, naming js files the same (consonantly) with the name of the page is very convenient. Or do I need to call one main from the other app? And what about the third one? :) And why does css work properly without a number?

**Comment by webdiscus** [comment]
All templates and resolved scripts in templates will be processed via Webpack entry option. So works Webpack.
Also all files in entry must have unique names to avoid indexing. My script allow you to use the same base filename for templates and scripts and self add an index if names are not unique.

after normalise of all resolved pages and scripts, internal Webpack entry is the following: 
```js
{
  index: 'src/home/index.html',
  'index.1': 'src/home/index.js', // <= has same base name 'index', therefore is added the unique index 
  main: 'src/scripts/main.js', 
  news: 'src/news/index.html',
  'index.2': 'src/news/index.js', // <= has same base name 'index', therefore is added the unique index 
}
```

Styles are processed separately, not via the entry option, bus if you add an style manually in Webpack entry, then it will be indexed too.

**Comment by exocornet** [comment]
> ```js
> index
> ```

Thanks for the explanation, but I thought that inside the plugin it would just be possible to solve it. But since I'm not a master at creating such plugins, I'm most likely mistaken.

Thanks for the detailed explanation!
