### ISSUE TITLE
Failed to generate common named chunk with enabled pug plugin

### ISSUE THREAD

**Issue by kbudasov** [webdiscus/pug-plugin#82]
Hi! I'd like to report an issue I've faced during the development.

I am using a lot of entry points, and I need a shared vendor chunk to extract libraries to it (provided from `node_modules`. In my configuration, it worked as expected, but when I used `PugPlugin` in the plugins section, the vendor chunk not generating anymore. 

Also, tried an example from the documentation to specify the file extension and many others. 

Please note, tried to build only scripts, separated from `.pug` entry points with enabled `pug-plugin`. Also, after applying the `pug-plugin` there are no generated "licence.txt" files, definitely because of the `extractComments: false` default option - so it impacts compiling even at least in that way.

Please, give me any advice on how to deal with it or request any additional info.

Link to Webpack config:
https://pastebin.com/BbZtp9QJ

Currently using this approach from the basic Webpack documentation:
https://webpack.js.org/plugins/split-chunks-plugin/#split-chunks-example-3

Thank you!

**Comment by kbudasov** [comment]
Let me clarify please,
yeah, I've read in the official documentation about the plugin compatibility issues. But still decided to try because I thought it will be okay if I will not use some functionality. For example: `mini-css-extract-plugin` was probably used to create `.css` as a separate file and `webpack-remove-empty-scripts` to clean empty `.js` that generates `mini-css-extract-plugin`. 
But I made a guess if I use the plugin with option `css: { enabled: false }`  probably plugins mentioned above will not be used/overwritten.
Same with javascripts - if pug-plugin is not used to compile "required" javascripts from the pug template, it shouldn't probably impact Webpack compilation methods.

In summary, expected flexibility and thought it's possible to use this plugin only to work with `.pug` files without impact on other areas. 

The current problem is `pug-plugin` somehow impacts javascripts compilation. At the same time, if I disable `.css` compilation from ].pug] plugins like `mini-css-extract-plugin` and `webpack-remove-empty-scripts`works as expected. I need so much to reach the same behavior with default scripts compiling if I use pug-loader only to create `.html`s.

Can you please give me some advice, what to do in this case? I like this plugin and won't trade it to abandoned `pug-loader`. Would it be a good solution to make a fork, add some conditions to prevent enabling some functionality to advance flexibility, and make a pull request? 

Thanks.

**Comment by webdiscus** [comment]
without a repo with reproducible issue, I can't help.
