### ISSUE TITLE
Invalid url when using full path "publicPath" option

### ISSUE THREAD

**Issue by var211** [webdiscus/pug-plugin#83]
https://github.com/webdiscus/pug-plugin/blob/9a78ba11d9fad37a50e8f18247c86ede0f1082c8/src/Asset.js#L100

Hello! I am not entirely sure but I found an issue that look like a bug to me.
In one of my projects I use CDN url in  **publicPath** webpack option which looks like this:

```
// ...
output: {
    path: path.join(__dirname, 'dist/'),
    publicPath: 'https://www.example.com/',
    clean: true
},
// ...
```

But in my html file it looks like this:

```
<link href="https:/www.example.com/static/css/display-9553306b629decdb02ed964372181d38.css" rel="stylesheet">
```
Further investigation showed that in `Asset.js` file `publicPath` concatination using function `path.posix.join`

And it looks like a source of the problem.

Test script:

```
const path = require('path');


const publicPath = 'https://www.example.com'
const assetFile = 'static/css/display-9553306b629decdb02ed964372181d38.css'

const result = path.posix.join(publicPath, assetFile)

console.log(result)

// outputs
// https:/www.example.com/static/css/display-9553306b629decdb02ed964372181d38.css

```

**Comment by var211** [comment]
Quick fix could be something like:

```
// ...
if (this.isUrlPublicPath) {
    let url = new URL(assetFile, this.publicPath);
    return url.href;
}
return path.posix.join(this.publicPath, assetFile);
// ...
```

**Comment by webdiscus** [comment]
Hello @var211,

Thanks for the bug report.

Can you please clarify:

 1. source code
 1. what is received
 2. what is expected

For example:

Config:
```js
output: {
    path: path.join(__dirname, 'dist/'),
    publicPath: 'https://www.example.com/',
},
```

Source:
```pug
link(href=require('./style.scss'))
```

Received:
```html
<link href="https:/www.example.com/static/css/display-9553306b629decdb02ed964372181d38.css" rel="stylesheet">
```

Expected:
```html
<link href="???" rel="stylesheet">
```

**Comment by var211** [comment]
Ok, sure.

Config:
```javascript
output: {
    path: path.join(__dirname, 'dist/'),
    publicPath: 'https://www.example.com/'
}
```
Source:

```pug
link(href=require('../css/display.css') rel='stylesheet')
```
Received:

```html
<link href="https:/www.example.com/css/display-a73fa0a651b8c02f99ee7b838473678b.css" rel="stylesheet">
```

Expected:

```html
<link href="https://www.example.com/css/display-a73fa0a651b8c02f99ee7b838473678b.css" rel="stylesheet">
```

Is it clear enough? Expected behavior is to leave `publicPath` unchanged. Current version removes second slash - `/` from `publicPath`.

**Comment by webdiscus** [comment]
@var211,

thanks for explain, I didn't attention to the slashes.

**Comment by webdiscus** [comment]
@var211 

in the v4.9.8 the bug is fixed.

Thank you!
